# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routing/v1alpha1/peer.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'routing/v1alpha1/peer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1brouting/v1alpha1/peer.proto\x12\x10routing.v1alpha1\"n\n\x04Peer\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05\x61\x64\x64rs\x18\x02 \x03(\tR\x05\x61\x64\x64rs\x12@\n\nconnection\x18\x03 \x01(\x0e\x32 .routing.v1alpha1.ConnectionTypeR\nconnection*\x97\x01\n\x0e\x43onnectionType\x12!\n\x1d\x43ONNECTION_TYPE_NOT_CONNECTED\x10\x00\x12\x1d\n\x19\x43ONNECTION_TYPE_CONNECTED\x10\x01\x12\x1f\n\x1b\x43ONNECTION_TYPE_CAN_CONNECT\x10\x02\x12\"\n\x1e\x43ONNECTION_TYPE_CANNOT_CONNECT\x10\x03\x42\xbe\x01\n\x14\x63om.routing.v1alpha1B\tPeerProtoP\x01Z:github.com/agntcy/dir/api/routing/v1alpha1;routingv1alpha1\xa2\x02\x03RXX\xaa\x02\x10Routing.V1alpha1\xca\x02\x10Routing\\V1alpha1\xe2\x02\x1cRouting\\V1alpha1\\GPBMetadata\xea\x02\x11Routing::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routing.v1alpha1.peer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.routing.v1alpha1B\tPeerProtoP\001Z:github.com/agntcy/dir/api/routing/v1alpha1;routingv1alpha1\242\002\003RXX\252\002\020Routing.V1alpha1\312\002\020Routing\\V1alpha1\342\002\034Routing\\V1alpha1\\GPBMetadata\352\002\021Routing::V1alpha1'
  _globals['_CONNECTIONTYPE']._serialized_start=162
  _globals['_CONNECTIONTYPE']._serialized_end=313
  _globals['_PEER']._serialized_start=49
  _globals['_PEER']._serialized_end=159
# @@protoc_insertion_point(module_scope)
