# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store/v1alpha2/record.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'store/v1alpha2/record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from store.v1alpha2 import object_pb2 as store_dot_v1alpha2_dot_object__pb2
from core.v1alpha1 import agent_pb2 as core_dot_v1alpha1_dot_agent__pb2
from core.v1alpha2 import record_pb2 as core_dot_v1alpha2_dot_record__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bstore/v1alpha2/record.proto\x12\x0estore.v1alpha2\x1a\x1bstore/v1alpha2/object.proto\x1a\x19\x63ore/v1alpha1/agent.proto\x1a\x1a\x63ore/v1alpha2/record.proto\"\x90\x01\n\x0cRecordObject\x12\x10\n\x03\x63id\x18\x01 \x01(\tR\x03\x63id\x12\x34\n\x04type\x18\x02 \x01(\x0e\x32 .store.v1alpha2.RecordObjectTypeR\x04type\x12\x38\n\x06record\x18\x03 \x01(\x0b\x32 .store.v1alpha2.RecordObjectDataR\x06record\"\x9d\x01\n\x10RecordObjectData\x12?\n\x0frecord_v1alpha1\x18\x01 \x01(\x0b\x32\x14.core.v1alpha1.AgentH\x00R\x0erecordV1alpha1\x12@\n\x0frecord_v1alpha2\x18\x02 \x01(\x0b\x32\x15.core.v1alpha2.RecordH\x00R\x0erecordV1alpha2B\x06\n\x04\x64\x61ta*\x8e\x01\n\x10RecordObjectType\x12\"\n\x1eRECORD_OBJECT_TYPE_UNSPECIFIED\x10\x00\x12*\n%RECORD_OBJECT_TYPE_OASF_V1ALPHA1_JSON\x10\xe9\x07\x12*\n%RECORD_OBJECT_TYPE_OASF_V1ALPHA2_JSON\x10\xea\x07\x32\xb5\x01\n\x13RecordObjectService\x12M\n\x15\x43onvertToRecordObject\x12\x16.store.v1alpha2.Object\x1a\x1c.store.v1alpha2.RecordObject\x12O\n\x17\x43onvertFromRecordObject\x12\x1c.store.v1alpha2.RecordObject\x1a\x16.store.v1alpha2.ObjectB\xb2\x01\n\x12\x63om.store.v1alpha2B\x0bRecordProtoP\x01Z6github.com/agntcy/dir/api/store/v1alpha2;storev1alpha2\xa2\x02\x03SXX\xaa\x02\x0eStore.V1alpha2\xca\x02\x0eStore\\V1alpha2\xe2\x02\x1aStore\\V1alpha2\\GPBMetadata\xea\x02\x0fStore::V1alpha2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store.v1alpha2.record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.store.v1alpha2B\013RecordProtoP\001Z6github.com/agntcy/dir/api/store/v1alpha2;storev1alpha2\242\002\003SXX\252\002\016Store.V1alpha2\312\002\016Store\\V1alpha2\342\002\032Store\\V1alpha2\\GPBMetadata\352\002\017Store::V1alpha2'
  _globals['_RECORDOBJECTTYPE']._serialized_start=439
  _globals['_RECORDOBJECTTYPE']._serialized_end=581
  _globals['_RECORDOBJECT']._serialized_start=132
  _globals['_RECORDOBJECT']._serialized_end=276
  _globals['_RECORDOBJECTDATA']._serialized_start=279
  _globals['_RECORDOBJECTDATA']._serialized_end=436
  _globals['_RECORDOBJECTSERVICE']._serialized_start=584
  _globals['_RECORDOBJECTSERVICE']._serialized_end=765
# @@protoc_insertion_point(module_scope)
