# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store/v1alpha2/store_service.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'store/v1alpha2/store_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from store.v1alpha2 import object_pb2 as store_dot_v1alpha2_dot_object__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"store/v1alpha2/store_service.proto\x12\x0estore.v1alpha2\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bstore/v1alpha2/object.proto2\x82\x02\n\x0cStoreService\x12;\n\x04Push\x12\x16.store.v1alpha2.Object\x1a\x19.store.v1alpha2.ObjectRef(\x01\x12;\n\x04Pull\x12\x19.store.v1alpha2.ObjectRef\x1a\x16.store.v1alpha2.Object0\x01\x12;\n\x06Lookup\x12\x19.store.v1alpha2.ObjectRef\x1a\x16.store.v1alpha2.Object\x12;\n\x06\x44\x65lete\x12\x19.store.v1alpha2.ObjectRef\x1a\x16.google.protobuf.EmptyB\xb8\x01\n\x12\x63om.store.v1alpha2B\x11StoreServiceProtoP\x01Z6github.com/agntcy/dir/api/store/v1alpha2;storev1alpha2\xa2\x02\x03SXX\xaa\x02\x0eStore.V1alpha2\xca\x02\x0eStore\\V1alpha2\xe2\x02\x1aStore\\V1alpha2\\GPBMetadata\xea\x02\x0fStore::V1alpha2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store.v1alpha2.store_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.store.v1alpha2B\021StoreServiceProtoP\001Z6github.com/agntcy/dir/api/store/v1alpha2;storev1alpha2\242\002\003SXX\252\002\016Store.V1alpha2\312\002\016Store\\V1alpha2\342\002\032Store\\V1alpha2\\GPBMetadata\352\002\017Store::V1alpha2'
  _globals['_STORESERVICE']._serialized_start=113
  _globals['_STORESERVICE']._serialized_end=371
# @@protoc_insertion_point(module_scope)
