# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from store.v1alpha2 import sync_service_pb2 as store_dot_v1alpha2_dot_sync__service__pb2


class SyncServiceStub(object):
    """SyncService provides functionality for synchronizing objects between Directory nodes.

    This service enables one-way synchronization from a remote Directory node to the local node,
    allowing distributed Directory instances to share and replicate objects. The service supports
    both on-demand synchronization and tracking of sync operations through their lifecycle.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSync = channel.unary_unary(
                '/store.v1alpha2.SyncService/CreateSync',
                request_serializer=store_dot_v1alpha2_dot_sync__service__pb2.CreateSyncRequest.SerializeToString,
                response_deserializer=store_dot_v1alpha2_dot_sync__service__pb2.CreateSyncResponse.FromString,
                _registered_method=True)
        self.ListSyncs = channel.unary_stream(
                '/store.v1alpha2.SyncService/ListSyncs',
                request_serializer=store_dot_v1alpha2_dot_sync__service__pb2.ListSyncsRequest.SerializeToString,
                response_deserializer=store_dot_v1alpha2_dot_sync__service__pb2.ListSyncItem.FromString,
                _registered_method=True)
        self.GetSync = channel.unary_unary(
                '/store.v1alpha2.SyncService/GetSync',
                request_serializer=store_dot_v1alpha2_dot_sync__service__pb2.GetSyncRequest.SerializeToString,
                response_deserializer=store_dot_v1alpha2_dot_sync__service__pb2.GetSyncResponse.FromString,
                _registered_method=True)
        self.DeleteSync = channel.unary_unary(
                '/store.v1alpha2.SyncService/DeleteSync',
                request_serializer=store_dot_v1alpha2_dot_sync__service__pb2.DeleteSyncRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SyncServiceServicer(object):
    """SyncService provides functionality for synchronizing objects between Directory nodes.

    This service enables one-way synchronization from a remote Directory node to the local node,
    allowing distributed Directory instances to share and replicate objects. The service supports
    both on-demand synchronization and tracking of sync operations through their lifecycle.
    """

    def CreateSync(self, request, context):
        """CreateSync initiates a new synchronization operation from a remote Directory node.

        The operation is non-blocking and returns immediately with a sync ID that can be used
        to track progress and manage the sync operation.

        Returns: A unique sync ID string for tracking the operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSyncs(self, request, context):
        """ListSyncs returns a stream of all sync operations known to the system.

        This includes active, completed, and failed synchronizations.

        Returns: A stream of sync IDs for all known synchronizations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSync(self, request, context):
        """GetSync retrieves detailed status information for a specific synchronization.

        Args: sync_id - The unique identifier of the sync operation
        Returns: Detailed status information for the specified sync
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSync(self, request, context):
        """DeleteSync removes a synchronization operation from the system.

        Args: sync_id - The unique identifier of the sync operation to delete
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSync': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSync,
                    request_deserializer=store_dot_v1alpha2_dot_sync__service__pb2.CreateSyncRequest.FromString,
                    response_serializer=store_dot_v1alpha2_dot_sync__service__pb2.CreateSyncResponse.SerializeToString,
            ),
            'ListSyncs': grpc.unary_stream_rpc_method_handler(
                    servicer.ListSyncs,
                    request_deserializer=store_dot_v1alpha2_dot_sync__service__pb2.ListSyncsRequest.FromString,
                    response_serializer=store_dot_v1alpha2_dot_sync__service__pb2.ListSyncItem.SerializeToString,
            ),
            'GetSync': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSync,
                    request_deserializer=store_dot_v1alpha2_dot_sync__service__pb2.GetSyncRequest.FromString,
                    response_serializer=store_dot_v1alpha2_dot_sync__service__pb2.GetSyncResponse.SerializeToString,
            ),
            'DeleteSync': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSync,
                    request_deserializer=store_dot_v1alpha2_dot_sync__service__pb2.DeleteSyncRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'store.v1alpha2.SyncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('store.v1alpha2.SyncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncService(object):
    """SyncService provides functionality for synchronizing objects between Directory nodes.

    This service enables one-way synchronization from a remote Directory node to the local node,
    allowing distributed Directory instances to share and replicate objects. The service supports
    both on-demand synchronization and tracking of sync operations through their lifecycle.
    """

    @staticmethod
    def CreateSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/store.v1alpha2.SyncService/CreateSync',
            store_dot_v1alpha2_dot_sync__service__pb2.CreateSyncRequest.SerializeToString,
            store_dot_v1alpha2_dot_sync__service__pb2.CreateSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSyncs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/store.v1alpha2.SyncService/ListSyncs',
            store_dot_v1alpha2_dot_sync__service__pb2.ListSyncsRequest.SerializeToString,
            store_dot_v1alpha2_dot_sync__service__pb2.ListSyncItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/store.v1alpha2.SyncService/GetSync',
            store_dot_v1alpha2_dot_sync__service__pb2.GetSyncRequest.SerializeToString,
            store_dot_v1alpha2_dot_sync__service__pb2.GetSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/store.v1alpha2.SyncService/DeleteSync',
            store_dot_v1alpha2_dot_sync__service__pb2.DeleteSyncRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
