run:
  timeout: 5m

linters:
  # Enable all available linters.
  # Default: false
  enable-all: true

  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - inamedparam # Allow unnamed args
    - funlen # Allow long functions
    - lll # Allow long lines
    - gochecknoglobals # Allow global variables
    - paralleltest # Allow missing t.Parallel() in tests
    - godox # Allow TODOs
    - tagliatelle # Allow json(camel)
    - gochecknoinits # Allow init function
    - nolintlint # Allow nolint
    - varnamelen # Allow short var names
    - ireturn # Allow returning with interfaces
    - exhaustruct # Allow structures with uninitialized fields
    - depguard # Allow all package imports
    - testpackage # Allow not having a test package
    - err113
    - tenv # deprecated

issues:
  exclude-rules:
    - path: types/adapters/record_oasfv.*\.go
      linters:
        - dupl

linters-settings:
  gomoddirectives:
    # Allow local `replace` directives. Default is false.
    replace-local: true

  cyclop:
    max-complexity: 15

  goheader:
    values:
      regexp:
        YEAR: 202[4-5]
    template: |-
      Copyright AGNTCY Contributors (https://github.com/agntcy)
      SPDX-License-Identifier: Apache-2.0
