# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/v1alpha2/locator.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'core/v1alpha2/locator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ore/v1alpha2/locator.proto\x12\rcore.v1alpha2\"\x84\x02\n\x07Locator\x12\x12\n\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n\x03url\x18\x02 \x01(\tR\x03url\x12I\n\x0b\x61nnotations\x18\x03 \x03(\x0b\x32\'.core.v1alpha2.Locator.AnnotationsEntryR\x0b\x61nnotations\x12\x17\n\x04size\x18\x04 \x01(\x04H\x00R\x04size\x88\x01\x01\x12\x1b\n\x06\x64igest\x18\x05 \x01(\tH\x01R\x06\x64igest\x88\x01\x01\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x07\n\x05_sizeB\t\n\x07_digest*\xbf\x01\n\x0bLocatorType\x12\x1c\n\x18LOCATOR_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17LOCATOR_TYPE_HELM_CHART\x10\x01\x12\x1d\n\x19LOCATOR_TYPE_DOCKER_IMAGE\x10\x02\x12\x1f\n\x1bLOCATOR_TYPE_PYTHON_PACKAGE\x10\x03\x12\x1c\n\x18LOCATOR_TYPE_SOURCE_CODE\x10\x04\x12\x17\n\x13LOCATOR_TYPE_BINARY\x10\x05\x42\xac\x01\n\x11\x63om.core.v1alpha2B\x0cLocatorProtoP\x01Z4github.com/agntcy/dir/api/core/v1alpha2;corev1alpha2\xa2\x02\x03\x43XX\xaa\x02\rCore.V1alpha2\xca\x02\rCore\\V1alpha2\xe2\x02\x19\x43ore\\V1alpha2\\GPBMetadata\xea\x02\x0e\x43ore::V1alpha2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.v1alpha2.locator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.core.v1alpha2B\014LocatorProtoP\001Z4github.com/agntcy/dir/api/core/v1alpha2;corev1alpha2\242\002\003CXX\252\002\rCore.V1alpha2\312\002\rCore\\V1alpha2\342\002\031Core\\V1alpha2\\GPBMetadata\352\002\016Core::V1alpha2'
  _globals['_LOCATOR_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_LOCATOR_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_LOCATORTYPE']._serialized_start=310
  _globals['_LOCATORTYPE']._serialized_end=501
  _globals['_LOCATOR']._serialized_start=47
  _globals['_LOCATOR']._serialized_end=307
  _globals['_LOCATOR_ANNOTATIONSENTRY']._serialized_start=225
  _globals['_LOCATOR_ANNOTATIONSENTRY']._serialized_end=287
# @@protoc_insertion_point(module_scope)
