# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/v1alpha2/record.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'core/v1alpha2/record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.v1alpha2 import skill_pb2 as core_dot_v1alpha2_dot_skill__pb2
from core.v1alpha2 import locator_pb2 as core_dot_v1alpha2_dot_locator__pb2
from core.v1alpha2 import extension_pb2 as core_dot_v1alpha2_dot_extension__pb2
from core.v1alpha2 import signature_pb2 as core_dot_v1alpha2_dot_signature__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ore/v1alpha2/record.proto\x12\rcore.v1alpha2\x1a\x19\x63ore/v1alpha2/skill.proto\x1a\x1b\x63ore/v1alpha2/locator.proto\x1a\x1d\x63ore/v1alpha2/extension.proto\x1a\x1d\x63ore/v1alpha2/signature.proto\"\xd0\x04\n\x06Record\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n\x07version\x18\x02 \x01(\tR\x07version\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12\x18\n\x07\x61uthors\x18\x04 \x03(\tR\x07\x61uthors\x12H\n\x0b\x61nnotations\x18\x05 \x03(\x0b\x32&.core.v1alpha2.Record.AnnotationsEntryR\x0b\x61nnotations\x12\x1d\n\ncreated_at\x18\x06 \x01(\tR\tcreatedAt\x12,\n\x06skills\x18\x07 \x03(\x0b\x32\x14.core.v1alpha2.SkillR\x06skills\x12\x32\n\x08locators\x18\x08 \x03(\x0b\x32\x16.core.v1alpha2.LocatorR\x08locators\x12\x38\n\nextensions\x18\t \x03(\x0b\x32\x18.core.v1alpha2.ExtensionR\nextensions\x12\x36\n\tsignature\x18\n \x01(\x0b\x32\x18.core.v1alpha2.SignatureR\tsignature\x12\x12\n\x04tags\x18\x0b \x03(\tR\x04tags\x12\x33\n\x13previous_record_cid\x18\x63 \x01(\tH\x00R\x11previousRecordCid\x88\x01\x01\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x16\n\x14_previous_record_cidB\xab\x01\n\x11\x63om.core.v1alpha2B\x0bRecordProtoP\x01Z4github.com/agntcy/dir/api/core/v1alpha2;corev1alpha2\xa2\x02\x03\x43XX\xaa\x02\rCore.V1alpha2\xca\x02\rCore\\V1alpha2\xe2\x02\x19\x43ore\\V1alpha2\\GPBMetadata\xea\x02\x0e\x43ore::V1alpha2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.v1alpha2.record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.core.v1alpha2B\013RecordProtoP\001Z4github.com/agntcy/dir/api/core/v1alpha2;corev1alpha2\242\002\003CXX\252\002\rCore.V1alpha2\312\002\rCore\\V1alpha2\342\002\031Core\\V1alpha2\\GPBMetadata\352\002\016Core::V1alpha2'
  _globals['_RECORD_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_RECORD_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_RECORD']._serialized_start=164
  _globals['_RECORD']._serialized_end=756
  _globals['_RECORD_ANNOTATIONSENTRY']._serialized_start=670
  _globals['_RECORD_ANNOTATIONSENTRY']._serialized_end=732
# @@protoc_insertion_point(module_scope)
