# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/v1alpha2/skill.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'core/v1alpha2/skill.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ore/v1alpha2/skill.proto\x12\rcore.v1alpha2\"\xb4\x01\n\x05Skill\x12\x0e\n\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12G\n\x0b\x61nnotations\x18\x03 \x03(\x0b\x32%.core.v1alpha2.Skill.AnnotationsEntryR\x0b\x61nnotations\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\xaa\x01\n\x11\x63om.core.v1alpha2B\nSkillProtoP\x01Z4github.com/agntcy/dir/api/core/v1alpha2;corev1alpha2\xa2\x02\x03\x43XX\xaa\x02\rCore.V1alpha2\xca\x02\rCore\\V1alpha2\xe2\x02\x19\x43ore\\V1alpha2\\GPBMetadata\xea\x02\x0e\x43ore::V1alpha2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.v1alpha2.skill_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.core.v1alpha2B\nSkillProtoP\001Z4github.com/agntcy/dir/api/core/v1alpha2;corev1alpha2\242\002\003CXX\252\002\rCore.V1alpha2\312\002\rCore\\V1alpha2\342\002\031Core\\V1alpha2\\GPBMetadata\352\002\016Core::V1alpha2'
  _globals['_SKILL_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_SKILL_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_SKILL']._serialized_start=45
  _globals['_SKILL']._serialized_end=225
  _globals['_SKILL_ANNOTATIONSENTRY']._serialized_start=163
  _globals['_SKILL_ANNOTATIONSENTRY']._serialized_end=225
# @@protoc_insertion_point(module_scope)
