# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/v1alpha1/object.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'core/v1alpha1/object.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from core.v1alpha1 import agent_pb2 as core_dot_v1alpha1_dot_agent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ore/v1alpha1/object.proto\x12\rcore.v1alpha1\x1a\x19\x63ore/v1alpha1/agent.proto\"\xd8\x01\n\tObjectRef\x12\x16\n\x06\x64igest\x18\x01 \x01(\tR\x06\x64igest\x12\x12\n\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n\x04size\x18\x03 \x01(\x04R\x04size\x12K\n\x0b\x61nnotations\x18\x04 \x03(\x0b\x32).core.v1alpha1.ObjectRef.AnnotationsEntryR\x0b\x61nnotations\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\x90\x01\n\x06Object\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\x0cR\x04\x64\x61ta\x12/\n\x03ref\x18\x02 \x01(\x0b\x32\x18.core.v1alpha1.ObjectRefH\x00R\x03ref\x88\x01\x01\x12/\n\x05\x61gent\x18\x03 \x01(\x0b\x32\x14.core.v1alpha1.AgentH\x01R\x05\x61gent\x88\x01\x01\x42\x06\n\x04_refB\x08\n\x06_agent*8\n\nObjectType\x12\x13\n\x0fOBJECT_TYPE_RAW\x10\x00\x12\x15\n\x11OBJECT_TYPE_AGENT\x10\x01\x42\xab\x01\n\x11\x63om.core.v1alpha1B\x0bObjectProtoP\x01Z4github.com/agntcy/dir/api/core/v1alpha1;corev1alpha1\xa2\x02\x03\x43XX\xaa\x02\rCore.V1alpha1\xca\x02\rCore\\V1alpha1\xe2\x02\x19\x43ore\\V1alpha1\\GPBMetadata\xea\x02\x0e\x43ore::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.v1alpha1.object_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.core.v1alpha1B\013ObjectProtoP\001Z4github.com/agntcy/dir/api/core/v1alpha1;corev1alpha1\242\002\003CXX\252\002\rCore.V1alpha1\312\002\rCore\\V1alpha1\342\002\031Core\\V1alpha1\\GPBMetadata\352\002\016Core::V1alpha1'
  _globals['_OBJECTREF_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_OBJECTREF_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_OBJECTTYPE']._serialized_start=438
  _globals['_OBJECTTYPE']._serialized_end=494
  _globals['_OBJECTREF']._serialized_start=73
  _globals['_OBJECTREF']._serialized_end=289
  _globals['_OBJECTREF_ANNOTATIONSENTRY']._serialized_start=227
  _globals['_OBJECTREF_ANNOTATIONSENTRY']._serialized_end=289
  _globals['_OBJECT']._serialized_start=292
  _globals['_OBJECT']._serialized_end=436
# @@protoc_insertion_point(module_scope)
