# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/v1alpha1/skill.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'core/v1alpha1/skill.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ore/v1alpha1/skill.proto\x12\rcore.v1alpha1\"\xbf\x02\n\x05Skill\x12G\n\x0b\x61nnotations\x18\x01 \x03(\x0b\x32%.core.v1alpha1.Skill.AnnotationsEntryR\x0b\x61nnotations\x12!\n\x0c\x63\x61tegory_uid\x18\x02 \x01(\x04R\x0b\x63\x61tegoryUid\x12\x1b\n\tclass_uid\x18\x03 \x01(\x04R\x08\x63lassUid\x12(\n\rcategory_name\x18\x04 \x01(\tH\x00R\x0c\x63\x61tegoryName\x88\x01\x01\x12\"\n\nclass_name\x18\x05 \x01(\tH\x01R\tclassName\x88\x01\x01\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x10\n\x0e_category_nameB\r\n\x0b_class_nameB\xaa\x01\n\x11\x63om.core.v1alpha1B\nSkillProtoP\x01Z4github.com/agntcy/dir/api/core/v1alpha1;corev1alpha1\xa2\x02\x03\x43XX\xaa\x02\rCore.V1alpha1\xca\x02\rCore\\V1alpha1\xe2\x02\x19\x43ore\\V1alpha1\\GPBMetadata\xea\x02\x0e\x43ore::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.v1alpha1.skill_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.core.v1alpha1B\nSkillProtoP\001Z4github.com/agntcy/dir/api/core/v1alpha1;corev1alpha1\242\002\003CXX\252\002\rCore.V1alpha1\312\002\rCore\\V1alpha1\342\002\031Core\\V1alpha1\\GPBMetadata\352\002\016Core::V1alpha1'
  _globals['_SKILL_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_SKILL_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_SKILL']._serialized_start=45
  _globals['_SKILL']._serialized_end=364
  _globals['_SKILL_ANNOTATIONSENTRY']._serialized_start=269
  _globals['_SKILL_ANNOTATIONSENTRY']._serialized_end=331
# @@protoc_insertion_point(module_scope)
