// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: agntcy/dir/sign/v1/public_key.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublicKey is the public key data associated with a Record.
// Multiple public keys can be associated with a single Record.
type PublicKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded public key string.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_agntcy_dir_sign_v1_public_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_agntcy_dir_sign_v1_public_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_agntcy_dir_sign_v1_public_key_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_agntcy_dir_sign_v1_public_key_proto protoreflect.FileDescriptor

var file_agntcy_dir_sign_v1_public_key_proto_rawDesc = string([]byte{
	0x0a, 0x23, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2f, 0x64, 0x69, 0x72, 0x2f, 0x73, 0x69, 0x67,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69,
	0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x1d, 0x0a, 0x09, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x42, 0xb6, 0x01, 0x0a, 0x16, 0x63, 0x6f, 0x6d,
	0x2e, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x64, 0x69, 0x72, 0x2e, 0x73, 0x69, 0x67, 0x6e,
	0x2e, 0x76, 0x31, 0x42, 0x0e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2f, 0x64, 0x69, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x73, 0x69, 0x67, 0x6e, 0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x44, 0x53, 0xaa, 0x02,
	0x12, 0x41, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x2e, 0x44, 0x69, 0x72, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x12, 0x41, 0x67, 0x6e, 0x74, 0x63, 0x79, 0x5c, 0x44, 0x69, 0x72,
	0x5c, 0x53, 0x69, 0x67, 0x6e, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1e, 0x41, 0x67, 0x6e, 0x74, 0x63,
	0x79, 0x5c, 0x44, 0x69, 0x72, 0x5c, 0x53, 0x69, 0x67, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x15, 0x41, 0x67, 0x6e, 0x74,
	0x63, 0x79, 0x3a, 0x3a, 0x44, 0x69, 0x72, 0x3a, 0x3a, 0x53, 0x69, 0x67, 0x6e, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_agntcy_dir_sign_v1_public_key_proto_rawDescOnce sync.Once
	file_agntcy_dir_sign_v1_public_key_proto_rawDescData []byte
)

func file_agntcy_dir_sign_v1_public_key_proto_rawDescGZIP() []byte {
	file_agntcy_dir_sign_v1_public_key_proto_rawDescOnce.Do(func() {
		file_agntcy_dir_sign_v1_public_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agntcy_dir_sign_v1_public_key_proto_rawDesc), len(file_agntcy_dir_sign_v1_public_key_proto_rawDesc)))
	})
	return file_agntcy_dir_sign_v1_public_key_proto_rawDescData
}

var file_agntcy_dir_sign_v1_public_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_agntcy_dir_sign_v1_public_key_proto_goTypes = []any{
	(*PublicKey)(nil), // 0: agntcy.dir.sign.v1.PublicKey
}
var file_agntcy_dir_sign_v1_public_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agntcy_dir_sign_v1_public_key_proto_init() }
func file_agntcy_dir_sign_v1_public_key_proto_init() {
	if File_agntcy_dir_sign_v1_public_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agntcy_dir_sign_v1_public_key_proto_rawDesc), len(file_agntcy_dir_sign_v1_public_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agntcy_dir_sign_v1_public_key_proto_goTypes,
		DependencyIndexes: file_agntcy_dir_sign_v1_public_key_proto_depIdxs,
		MessageInfos:      file_agntcy_dir_sign_v1_public_key_proto_msgTypes,
	}.Build()
	File_agntcy_dir_sign_v1_public_key_proto = out.File
	file_agntcy_dir_sign_v1_public_key_proto_goTypes = nil
	file_agntcy_dir_sign_v1_public_key_proto_depIdxs = nil
}
