# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routing/v1alpha2/peer.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'routing/v1alpha2/peer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1brouting/v1alpha2/peer.proto\x12\x10routing.v1alpha2\"\xfd\x01\n\x04Peer\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05\x61\x64\x64rs\x18\x02 \x03(\tR\x05\x61\x64\x64rs\x12I\n\x0b\x61nnotations\x18\x03 \x03(\x0b\x32\'.routing.v1alpha2.Peer.AnnotationsEntryR\x0b\x61nnotations\x12\x44\n\nconnection\x18\x04 \x01(\x0e\x32$.routing.v1alpha2.PeerConnectionTypeR\nconnection\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01*\xaf\x01\n\x12PeerConnectionType\x12&\n\"PEER_CONNECTION_TYPE_NOT_CONNECTED\x10\x00\x12\"\n\x1ePEER_CONNECTION_TYPE_CONNECTED\x10\x01\x12$\n PEER_CONNECTION_TYPE_CAN_CONNECT\x10\x02\x12\'\n#PEER_CONNECTION_TYPE_CANNOT_CONNECT\x10\x03\x42\xbe\x01\n\x14\x63om.routing.v1alpha2B\tPeerProtoP\x01Z:github.com/agntcy/dir/api/routing/v1alpha2;routingv1alpha2\xa2\x02\x03RXX\xaa\x02\x10Routing.V1alpha2\xca\x02\x10Routing\\V1alpha2\xe2\x02\x1cRouting\\V1alpha2\\GPBMetadata\xea\x02\x11Routing::V1alpha2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routing.v1alpha2.peer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.routing.v1alpha2B\tPeerProtoP\001Z:github.com/agntcy/dir/api/routing/v1alpha2;routingv1alpha2\242\002\003RXX\252\002\020Routing.V1alpha2\312\002\020Routing\\V1alpha2\342\002\034Routing\\V1alpha2\\GPBMetadata\352\002\021Routing::V1alpha2'
  _globals['_PEER_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_PEER_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_PEERCONNECTIONTYPE']._serialized_start=306
  _globals['_PEERCONNECTIONTYPE']._serialized_end=481
  _globals['_PEER']._serialized_start=50
  _globals['_PEER']._serialized_end=303
  _globals['_PEER_ANNOTATIONSENTRY']._serialized_start=241
  _globals['_PEER_ANNOTATIONSENTRY']._serialized_end=303
# @@protoc_insertion_point(module_scope)
