# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routing/v1alpha2/record_query.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'routing/v1alpha2/record_query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#routing/v1alpha2/record_query.proto\x12\x10routing.v1alpha2\"Z\n\x0bRecordQuery\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32!.routing.v1alpha2.RecordQueryTypeR\x04type\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value*p\n\x0fRecordQueryType\x12!\n\x1dRECORD_QUERY_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17RECORD_QUERY_TYPE_SKILL\x10\x01\x12\x1d\n\x19RECORD_QUERY_TYPE_LOCATOR\x10\x02\x42\xc5\x01\n\x14\x63om.routing.v1alpha2B\x10RecordQueryProtoP\x01Z:github.com/agntcy/dir/api/routing/v1alpha2;routingv1alpha2\xa2\x02\x03RXX\xaa\x02\x10Routing.V1alpha2\xca\x02\x10Routing\\V1alpha2\xe2\x02\x1cRouting\\V1alpha2\\GPBMetadata\xea\x02\x11Routing::V1alpha2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routing.v1alpha2.record_query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.routing.v1alpha2B\020RecordQueryProtoP\001Z:github.com/agntcy/dir/api/routing/v1alpha2;routingv1alpha2\242\002\003RXX\252\002\020Routing.V1alpha2\312\002\020Routing\\V1alpha2\342\002\034Routing\\V1alpha2\\GPBMetadata\352\002\021Routing::V1alpha2'
  _globals['_RECORDQUERYTYPE']._serialized_start=149
  _globals['_RECORDQUERYTYPE']._serialized_end=261
  _globals['_RECORDQUERY']._serialized_start=57
  _globals['_RECORDQUERY']._serialized_end=147
# @@protoc_insertion_point(module_scope)
