# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routing/v1alpha2/routing_service.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'routing/v1alpha2/routing_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from routing.v1alpha2 import peer_pb2 as routing_dot_v1alpha2_dot_peer__pb2
from routing.v1alpha2 import record_query_pb2 as routing_dot_v1alpha2_dot_record__query__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&routing/v1alpha2/routing_service.proto\x12\x10routing.v1alpha2\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1brouting/v1alpha2/peer.proto\x1a#routing/v1alpha2/record_query.proto\"/\n\x0ePublishRequest\x12\x1d\n\nrecord_cid\x18\x01 \x01(\tR\trecordCid\"1\n\x10UnpublishRequest\x12\x1d\n\nrecord_cid\x18\x01 \x01(\tR\trecordCid\"\xae\x01\n\rSearchRequest\x12\x37\n\x07queries\x18\x01 \x03(\x0b\x32\x1d.routing.v1alpha2.RecordQueryR\x07queries\x12+\n\x0fmin_match_score\x18\x02 \x01(\rH\x00R\rminMatchScore\x88\x01\x01\x12\x19\n\x05limit\x18\x03 \x01(\rH\x01R\x05limit\x88\x01\x01\x42\x12\n\x10_min_match_scoreB\x08\n\x06_limit\"\xc0\x01\n\x0eSearchResponse\x12\x1d\n\nrecord_cid\x18\x01 \x01(\tR\trecordCid\x12*\n\x04peer\x18\x02 \x01(\x0b\x32\x16.routing.v1alpha2.PeerR\x04peer\x12\x42\n\rmatch_queries\x18\x03 \x03(\x0b\x32\x1d.routing.v1alpha2.RecordQueryR\x0cmatchQueries\x12\x1f\n\x0bmatch_score\x18\x04 \x01(\rR\nmatchScore\"k\n\x0bListRequest\x12\x37\n\x07queries\x18\x01 \x03(\x0b\x32\x1d.routing.v1alpha2.RecordQueryR\x07queries\x12\x19\n\x05limit\x18\x02 \x01(\rH\x00R\x05limit\x88\x01\x01\x42\x08\n\x06_limit\"-\n\x0cListResponse\x12\x1d\n\nrecord_cid\x18\x01 \x01(\tR\trecordCid2\xb6\x02\n\x0eRoutingService\x12\x43\n\x07Publish\x12 .routing.v1alpha2.PublishRequest\x1a\x16.google.protobuf.Empty\x12G\n\tUnpublish\x12\".routing.v1alpha2.UnpublishRequest\x1a\x16.google.protobuf.Empty\x12M\n\x06Search\x12\x1f.routing.v1alpha2.SearchRequest\x1a .routing.v1alpha2.SearchResponse0\x01\x12G\n\x04List\x12\x1d.routing.v1alpha2.ListRequest\x1a\x1e.routing.v1alpha2.ListResponse0\x01\x42\xc8\x01\n\x14\x63om.routing.v1alpha2B\x13RoutingServiceProtoP\x01Z:github.com/agntcy/dir/api/routing/v1alpha2;routingv1alpha2\xa2\x02\x03RXX\xaa\x02\x10Routing.V1alpha2\xca\x02\x10Routing\\V1alpha2\xe2\x02\x1cRouting\\V1alpha2\\GPBMetadata\xea\x02\x11Routing::V1alpha2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routing.v1alpha2.routing_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.routing.v1alpha2B\023RoutingServiceProtoP\001Z:github.com/agntcy/dir/api/routing/v1alpha2;routingv1alpha2\242\002\003RXX\252\002\020Routing.V1alpha2\312\002\020Routing\\V1alpha2\342\002\034Routing\\V1alpha2\\GPBMetadata\352\002\021Routing::V1alpha2'
  _globals['_PUBLISHREQUEST']._serialized_start=155
  _globals['_PUBLISHREQUEST']._serialized_end=202
  _globals['_UNPUBLISHREQUEST']._serialized_start=204
  _globals['_UNPUBLISHREQUEST']._serialized_end=253
  _globals['_SEARCHREQUEST']._serialized_start=256
  _globals['_SEARCHREQUEST']._serialized_end=430
  _globals['_SEARCHRESPONSE']._serialized_start=433
  _globals['_SEARCHRESPONSE']._serialized_end=625
  _globals['_LISTREQUEST']._serialized_start=627
  _globals['_LISTREQUEST']._serialized_end=734
  _globals['_LISTRESPONSE']._serialized_start=736
  _globals['_LISTRESPONSE']._serialized_end=781
  _globals['_ROUTINGSERVICE']._serialized_start=784
  _globals['_ROUTINGSERVICE']._serialized_end=1094
# @@protoc_insertion_point(module_scope)
