# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search/v1alpha2/record_query.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'search/v1alpha2/record_query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"search/v1alpha2/record_query.proto\x12\x0fsearch.v1alpha2\"Y\n\x0bRecordQuery\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32 .search.v1alpha2.RecordQueryTypeR\x04type\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value*\xf1\x01\n\x0fRecordQueryType\x12!\n\x1dRECORD_QUERY_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16RECORD_QUERY_TYPE_NAME\x10\x01\x12\x1d\n\x19RECORD_QUERY_TYPE_VERSION\x10\x02\x12\x1e\n\x1aRECORD_QUERY_TYPE_SKILL_ID\x10\x03\x12 \n\x1cRECORD_QUERY_TYPE_SKILL_NAME\x10\x04\x12\x1d\n\x19RECORD_QUERY_TYPE_LOCATOR\x10\x05\x12\x1f\n\x1bRECORD_QUERY_TYPE_EXTENSION\x10\x06\x42\xbe\x01\n\x13\x63om.search.v1alpha2B\x10RecordQueryProtoP\x01Z8github.com/agntcy/dir/api/search/v1alpha2;searchv1alpha2\xa2\x02\x03SXX\xaa\x02\x0fSearch.V1alpha2\xca\x02\x0fSearch\\V1alpha2\xe2\x02\x1bSearch\\V1alpha2\\GPBMetadata\xea\x02\x10Search::V1alpha2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search.v1alpha2.record_query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.search.v1alpha2B\020RecordQueryProtoP\001Z8github.com/agntcy/dir/api/search/v1alpha2;searchv1alpha2\242\002\003SXX\252\002\017Search.V1alpha2\312\002\017Search\\V1alpha2\342\002\033Search\\V1alpha2\\GPBMetadata\352\002\020Search::V1alpha2'
  _globals['_RECORDQUERYTYPE']._serialized_start=147
  _globals['_RECORDQUERYTYPE']._serialized_end=388
  _globals['_RECORDQUERY']._serialized_start=55
  _globals['_RECORDQUERY']._serialized_end=144
# @@protoc_insertion_point(module_scope)
