// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: objectmanager/record.proto

package objectmanager

import (
	context "context"
	v1alpha2 "github.com/agntcy/dir/api/store/v1alpha2"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RecordObjectConverter_ConvertToRecordObject_FullMethodName   = "/objectmanager.RecordObjectConverter/ConvertToRecordObject"
	RecordObjectConverter_ConvertFromRecordObject_FullMethodName = "/objectmanager.RecordObjectConverter/ConvertFromRecordObject"
)

// RecordObjectConverterClient is the client API for RecordObjectConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Converts Object to an RecordObject and vice versa.
// This is client-side service only.
type RecordObjectConverterClient interface {
	// Converts an Object to a RecordObject.
	ConvertToRecordObject(ctx context.Context, in *v1alpha2.Object, opts ...grpc.CallOption) (*RecordObject, error)
	// Converts a RecordObject to an Object.
	ConvertFromRecordObject(ctx context.Context, in *RecordObject, opts ...grpc.CallOption) (*v1alpha2.Object, error)
}

type recordObjectConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordObjectConverterClient(cc grpc.ClientConnInterface) RecordObjectConverterClient {
	return &recordObjectConverterClient{cc}
}

func (c *recordObjectConverterClient) ConvertToRecordObject(ctx context.Context, in *v1alpha2.Object, opts ...grpc.CallOption) (*RecordObject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordObject)
	err := c.cc.Invoke(ctx, RecordObjectConverter_ConvertToRecordObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordObjectConverterClient) ConvertFromRecordObject(ctx context.Context, in *RecordObject, opts ...grpc.CallOption) (*v1alpha2.Object, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1alpha2.Object)
	err := c.cc.Invoke(ctx, RecordObjectConverter_ConvertFromRecordObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordObjectConverterServer is the server API for RecordObjectConverter service.
// All implementations should embed UnimplementedRecordObjectConverterServer
// for forward compatibility.
//
// Converts Object to an RecordObject and vice versa.
// This is client-side service only.
type RecordObjectConverterServer interface {
	// Converts an Object to a RecordObject.
	ConvertToRecordObject(context.Context, *v1alpha2.Object) (*RecordObject, error)
	// Converts a RecordObject to an Object.
	ConvertFromRecordObject(context.Context, *RecordObject) (*v1alpha2.Object, error)
}

// UnimplementedRecordObjectConverterServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordObjectConverterServer struct{}

func (UnimplementedRecordObjectConverterServer) ConvertToRecordObject(context.Context, *v1alpha2.Object) (*RecordObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertToRecordObject not implemented")
}
func (UnimplementedRecordObjectConverterServer) ConvertFromRecordObject(context.Context, *RecordObject) (*v1alpha2.Object, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertFromRecordObject not implemented")
}
func (UnimplementedRecordObjectConverterServer) testEmbeddedByValue() {}

// UnsafeRecordObjectConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordObjectConverterServer will
// result in compilation errors.
type UnsafeRecordObjectConverterServer interface {
	mustEmbedUnimplementedRecordObjectConverterServer()
}

func RegisterRecordObjectConverterServer(s grpc.ServiceRegistrar, srv RecordObjectConverterServer) {
	// If the following call pancis, it indicates UnimplementedRecordObjectConverterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordObjectConverter_ServiceDesc, srv)
}

func _RecordObjectConverter_ConvertToRecordObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1alpha2.Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordObjectConverterServer).ConvertToRecordObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordObjectConverter_ConvertToRecordObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordObjectConverterServer).ConvertToRecordObject(ctx, req.(*v1alpha2.Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordObjectConverter_ConvertFromRecordObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordObjectConverterServer).ConvertFromRecordObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordObjectConverter_ConvertFromRecordObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordObjectConverterServer).ConvertFromRecordObject(ctx, req.(*RecordObject))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordObjectConverter_ServiceDesc is the grpc.ServiceDesc for RecordObjectConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordObjectConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "objectmanager.RecordObjectConverter",
	HandlerType: (*RecordObjectConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertToRecordObject",
			Handler:    _RecordObjectConverter_ConvertToRecordObject_Handler,
		},
		{
			MethodName: "ConvertFromRecordObject",
			Handler:    _RecordObjectConverter_ConvertFromRecordObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "objectmanager/record.proto",
}
